replicaCount: 1

image:
  repository: nginx
  tag: 1.28

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: myapp.ac1c0f56ce58946b585c045a7801455a-204078258.us-east-1.elb.amazonaws.com.nip.io
